version: '3'
services:
  web:
    image: wartexnik/news-sentiment-team-knocks:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - NEWSAPI_KEY=YOUR_API_KEY
      - OPENAI_API_KEY=YOUR_API_KEY